{% set name = "django-handyhelpers" %}
{% set version = "0.3.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 67fd9b6c362a8f305eb6a1b3dfad15cc33c2dca425ed0cbd39a7e804c7294561

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=3.2
    - djangorestframework
    - djangorestframework-filters ==1.0.0.dev0
    - drf-dynamic-fields
    - hurry.filesize
    - jinja2
    - markupsafe
    - python-dateutil
    - pytz
    - sqlparse
    - xlwt ==1.3.0

test:
  imports:
    - handyhelpers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davidslusser/django-handyhelpers
  summary: A collection of handy utilities to support django operations
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
