{% set name = "django-handyhelpers" %}
{% set version = "0.3.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_handyhelpers-{{ version }}.tar.gz
  sha256: 493a954509c1837fb35cc3d8450b7b638ae68c300161771f751622e4e12b4308

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django
    - djangorestframework
    - djangorestframework-filters ==1.0.0.dev0
    - drf-dynamic-fields
    - hurry.filesize
    - jinja2
    - markupsafe
    - python-dateutil
    - sqlparse
    - xlwt ==1.3.0

test:
  imports:
    - handyhelpers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/davidslusser/django-handyhelpers
  summary: A collection of handy utilities to support django operations
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
